/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veri_tabani_depo;


import java.util.ArrayList;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;

/**
 *
 * @author numan
 */
public class gidergirisi extends javax.swing.JFrame {
Integer val;
   static Session session=null;
  static  SessionFactory sessionFactory=null;
   static Transaction tx ;
    /**
     * Creates new form Gider_Girisi
     */
    public gidergirisi() {
        initComponents();
        this.setBounds(500, 100, 430    , 350);
    }

      
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        aciklama3 = new javax.swing.JTextField();
        jText_Kime4 = new javax.swing.JTextField();
        Jcombo_Turu4 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jText_Tutar4 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        aciklama = new javax.swing.JTextField();
        Jcombo_Turu3 = new javax.swing.JComboBox<>();
        jText_Kime3 = new javax.swing.JTextField();
        jText_Tutar3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 0));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 947, 1305, 0);

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        jPanel6.setLayout(null);

        aciklama3.setBackground(new java.awt.Color(204, 204, 204));
        aciklama3.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        aciklama3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aciklama3ActionPerformed(evt);
            }
        });
        jPanel6.add(aciklama3);
        aciklama3.setBounds(150, 170, 250, 40);

        jText_Kime4.setBackground(new java.awt.Color(204, 204, 204));
        jText_Kime4.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jPanel6.add(jText_Kime4);
        jText_Kime4.setBounds(150, 110, 250, 40);

        Jcombo_Turu4.setBackground(new java.awt.Color(204, 204, 204));
        Jcombo_Turu4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        Jcombo_Turu4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nakit", "Kart", "Cek/senet" }));
        Jcombo_Turu4.setAutoscrolls(true);
        Jcombo_Turu4.setDoubleBuffered(true);
        Jcombo_Turu4.setFocusCycleRoot(true);
        Jcombo_Turu4.setFocusTraversalPolicyProvider(true);
        Jcombo_Turu4.setInheritsPopupMenu(true);
        Jcombo_Turu4.setOpaque(false);
        jPanel6.add(Jcombo_Turu4);
        Jcombo_Turu4.setBounds(150, 10, 250, 42);

        jLabel20.setFont(jLabel20.getFont().deriveFont(jLabel20.getFont().getStyle() | java.awt.Font.BOLD, 24));
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Acıklama");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(10, 180, 150, 29);

        jText_Tutar4.setBackground(new java.awt.Color(204, 204, 204));
        jText_Tutar4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jText_Tutar4.setDoubleBuffered(true);
        jText_Tutar4.setDragEnabled(true);
        jText_Tutar4.setFocusTraversalPolicyProvider(true);
        jPanel6.add(jText_Tutar4);
        jText_Tutar4.setBounds(150, 60, 250, 40);

        jLabel22.setFont(jLabel22.getFont().deriveFont(jLabel22.getFont().getStyle() | java.awt.Font.BOLD, 24));
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Tutar");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(10, 60, 134, 40);

        jLabel21.setFont(jLabel21.getFont().deriveFont(jLabel21.getFont().getStyle() | java.awt.Font.BOLD, 24));
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Kime");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(10, 120, 146, 39);

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | java.awt.Font.BOLD, 24));
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Türü");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(10, 10, 120, 29);

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setText("Kaydet");
        jButton5.setToolTipText("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5);
        jButton5.setBounds(0, 240, 390, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\İmage\\Beyaz.jpg")); // NOI18N
        jPanel6.add(jLabel4);
        jLabel4.setBounds(0, 0, 410, 280);

        jTabbedPane2.addTab("Gerlir İşlemleri", jPanel6);

        jPanel5.setLayout(null);

        jLabel25.setFont(jLabel25.getFont().deriveFont(jLabel25.getFont().getStyle() | java.awt.Font.BOLD, 24));
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Acıklama");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(10, 180, 150, 29);

        jLabel24.setFont(jLabel24.getFont().deriveFont(jLabel24.getFont().getStyle() | java.awt.Font.BOLD, 24));
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Kime");
        jPanel5.add(jLabel24);
        jLabel24.setBounds(10, 120, 146, 39);

        jLabel23.setFont(jLabel23.getFont().deriveFont(jLabel23.getFont().getStyle() | java.awt.Font.BOLD, 24));
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Tutar");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(10, 60, 134, 40);

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getStyle() | java.awt.Font.BOLD, 24));
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Türü");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(10, 10, 120, 29);

        aciklama.setBackground(new java.awt.Color(204, 204, 204));
        aciklama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aciklama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aciklamaActionPerformed(evt);
            }
        });
        jPanel5.add(aciklama);
        aciklama.setBounds(150, 160, 260, 50);

        Jcombo_Turu3.setBackground(new java.awt.Color(204, 204, 204));
        Jcombo_Turu3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        Jcombo_Turu3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nakit", "Kart", "Cek/senet" }));
        Jcombo_Turu3.setAutoscrolls(true);
        Jcombo_Turu3.setDoubleBuffered(true);
        Jcombo_Turu3.setFocusCycleRoot(true);
        Jcombo_Turu3.setFocusTraversalPolicyProvider(true);
        Jcombo_Turu3.setInheritsPopupMenu(true);
        jPanel5.add(Jcombo_Turu3);
        Jcombo_Turu3.setBounds(150, 10, 250, 42);

        jText_Kime3.setBackground(new java.awt.Color(204, 204, 204));
        jText_Kime3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel5.add(jText_Kime3);
        jText_Kime3.setBounds(150, 110, 260, 40);

        jText_Tutar3.setBackground(new java.awt.Color(204, 204, 204));
        jText_Tutar3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jPanel5.add(jText_Tutar3);
        jText_Tutar3.setBounds(150, 60, 260, 40);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setText("Kaydet");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);
        jButton4.setBounds(0, 240, 390, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\İmage\\Beyaz.jpg")); // NOI18N
        jPanel5.add(jLabel3);
        jLabel3.setBounds(-10, 0, 460, 360);

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getStyle() | java.awt.Font.BOLD, 24));
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Türü");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(10, 10, 120, 29);

        jTabbedPane2.addTab("Giden İslemleri", jPanel5);

        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String Sorgu="INSERT kasa (`Gelir-Giden`, Acıklama, Miktar, Kime_Kimden,Turu) VALUES (0, ?, ?, ?,?)";
        java.util.ArrayList<String>dizi=new  java.util.ArrayList<>();
        String a=(String) Jcombo_Turu4.getSelectedItem();

        dizi.add(aciklama3.getText());
        dizi.add(jText_Tutar4.getText());
        dizi.add(jText_Kime4.getText());

        dizi.add(a);

        Veri_Ekleme ekleme=new Veri_Ekleme();
        ekleme.kaydet(dizi, Sorgu);

       

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void aciklama3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aciklama3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aciklama3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String Sorgu="INSERT kasa (`Gelir-Giden`, Acıklama, Miktar, Kime_Kimden,Turu) VALUES (1, ?, ?, ?,?)";
        java.util.ArrayList<String>dizi=new  java.util.ArrayList<>();
        String a=(String) Jcombo_Turu3.getSelectedItem();

        dizi.add(aciklama.getText());
        dizi.add(jText_Tutar3.getText());
        dizi.add(jText_Kime3.getText());

        dizi.add(a);

        Veri_Ekleme ekleme=new Veri_Ekleme();
        ekleme.kaydet(dizi, Sorgu);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void aciklamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aciklamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aciklamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gidergirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gidergirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gidergirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gidergirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gidergirisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Jcombo_Turu3;
    private javax.swing.JComboBox<String> Jcombo_Turu4;
    private javax.swing.JTextField aciklama;
    private javax.swing.JTextField aciklama3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jText_Kime3;
    private javax.swing.JTextField jText_Kime4;
    private javax.swing.JTextField jText_Tutar3;
    private javax.swing.JTextField jText_Tutar4;
    // End of variables declaration//GEN-END:variables
}
