/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veri_tabani_depo;

import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author numan
 */
public class kullanicigirisi extends javax.swing.JFrame {

    /**
     * Creates new form Kullanıcı_Girisi
     */
    public kullanicigirisi() {
        initComponents();
        this.setTitle("Üye Girişi");
     
         this.setBounds(960, 100, 650, 400);

          setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField_Tc = new javax.swing.JTextField();
        jTextField_Sifre = new javax.swing.JTextField();
        jLabel_Tc = new javax.swing.JLabel();
        Tc_jLabel = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(153, 51, 0));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Giris");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 200, 130, 29);

        jButton2.setBackground(new java.awt.Color(153, 51, 0));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cıkıs");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 200, 130, 29);

        jTextField_Tc.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jTextField_Tc.setForeground(new java.awt.Color(153, 51, 0));
        getContentPane().add(jTextField_Tc);
        jTextField_Tc.setBounds(380, 90, 120, 31);

        jTextField_Sifre.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jTextField_Sifre.setForeground(new java.awt.Color(153, 51, 0));
        getContentPane().add(jTextField_Sifre);
        jTextField_Sifre.setBounds(380, 150, 120, 31);

        jLabel_Tc.setBackground(new java.awt.Color(153, 51, 0));
        jLabel_Tc.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel_Tc.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Tc.setText("Tc.Numarasi");
        jLabel_Tc.setOpaque(true);
        getContentPane().add(jLabel_Tc);
        jLabel_Tc.setBounds(230, 90, 120, 25);

        Tc_jLabel.setBackground(new java.awt.Color(153, 51, 0));
        Tc_jLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        Tc_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        Tc_jLabel.setText("       Sifre");
        Tc_jLabel.setOpaque(true);
        getContentPane().add(Tc_jLabel);
        Tc_jLabel.setBounds(240, 150, 110, 20);

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\depo2.png")); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 610, 381);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));           // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String b="1";
        Veri_Cekme cekme=new Veri_Cekme();
        try {
            cekme.Veri_Cekme("SELECT COUNT(tc) from personeller WHERE tc='"+jTextField_Tc.getText()+"' AND Sifre='"+jTextField_Sifre.getText()+"' AND Yetki='1'");
            
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(kullanicigirisi.class.getName()).log(Level.SEVERE, null, ex);
        }
        int a=Integer.valueOf(cekme.getRow().get(0));
        if (a==1) {
          AnaSayfa_ anaSayfa_=new AnaSayfa_();
          anaSayfa_.setVisible(true);
        }
        else{
               JOptionPane.showMessageDialog(null, "Tc veye Sifreyi Yanlıs Girdiniz");
   
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kullanicigirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kullanicigirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kullanicigirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kullanicigirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kullanicigirisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Tc_jLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel_Tc;
    private javax.swing.JTextField jTextField_Sifre;
    private javax.swing.JTextField jTextField_Tc;
    // End of variables declaration//GEN-END:variables
}
