/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veri_tabani_depo;

import java.util.ArrayList;

/**
 *
 * @author numan
 */
public class Musteri_EKle extends javax.swing.JFrame {

    /**
     * Creates new form Musteriler_Menusu
     */
    public Musteri_EKle() {
        initComponents();
       
           this.setTitle("Müşteri Ekle");
     
         this.setBounds(960, 100, 350, 550);

          setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Tc_jTextField = new javax.swing.JTextField();
        CepTelefonu_jTextField = new javax.swing.JTextField();
        Yetkili_Kisi_jTextField = new javax.swing.JTextField();
        Iban_jTextField = new javax.swing.JTextField();
        SabitTelefon_jTextField = new javax.swing.JTextField();
        Sirket_Ad_jTextField = new javax.swing.JTextField();
        EPosta_jTextField = new javax.swing.JTextField();
        VergiDairesi_jTextField = new javax.swing.JTextField();
        VergiNumarasi_jTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Adres_jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButtoncikis = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(153, 51, 0));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("Tc");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 40, 90, 25);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("Sabit Telefon");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 110, 100, 25);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText("E-Posta");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 270, 100, 20);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("Adres");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 190, 100, 25);

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText("Yetkili Kişi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 70, 100, 30);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 0));
        jLabel6.setText("Sirket Adi");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 230, 90, 25);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setText("Vergi Dairesi");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 300, 110, 25);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 51, 0));
        jLabel8.setText("Iban Numarasi");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 380, 150, 20);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 51, 0));
        jLabel9.setText("Vergi Numarasi");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 340, 140, 20);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 51, 0));
        jLabel10.setText("Cep Telefonu");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 150, 120, 20);
        getContentPane().add(Tc_jTextField);
        Tc_jTextField.setBounds(130, 40, 190, 22);
        getContentPane().add(CepTelefonu_jTextField);
        CepTelefonu_jTextField.setBounds(130, 150, 190, 22);
        getContentPane().add(Yetkili_Kisi_jTextField);
        Yetkili_Kisi_jTextField.setBounds(130, 70, 190, 22);
        getContentPane().add(Iban_jTextField);
        Iban_jTextField.setBounds(140, 380, 180, 22);
        getContentPane().add(SabitTelefon_jTextField);
        SabitTelefon_jTextField.setBounds(130, 110, 190, 22);
        getContentPane().add(Sirket_Ad_jTextField);
        Sirket_Ad_jTextField.setBounds(130, 230, 190, 22);
        getContentPane().add(EPosta_jTextField);
        EPosta_jTextField.setBounds(130, 260, 190, 22);
        getContentPane().add(VergiDairesi_jTextField);
        VergiDairesi_jTextField.setBounds(130, 300, 190, 22);
        getContentPane().add(VergiNumarasi_jTextField);
        VergiNumarasi_jTextField.setBounds(130, 340, 190, 22);

        jScrollPane1.setViewportView(Adres_jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 190, 190, 24);

        jButton1.setBackground(new java.awt.Color(153, 51, 0));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\save.png")); // NOI18N
        jButton1.setText("Kaydet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 430, 110, 30);

        jButton2.setBackground(new java.awt.Color(153, 51, 0));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\delete-2.png")); // NOI18N
        jButton2.setText("Temizle");
        getContentPane().add(jButton2);
        jButton2.setBounds(100, 430, 130, 30);

        jLabel11.setBackground(new java.awt.Color(153, 51, 0));
        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("                         Müsteri Ekleme Sayfasi");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 10, 350, 20);

        jButtoncikis.setBackground(new java.awt.Color(153, 51, 0));
        jButtoncikis.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButtoncikis.setForeground(new java.awt.Color(255, 255, 255));
        jButtoncikis.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\exit-2.png")); // NOI18N
        jButtoncikis.setText("Cıkıs");
        jButtoncikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncikisActionPerformed(evt);
            }
        });
        getContentPane().add(jButtoncikis);
        jButtoncikis.setBounds(0, 430, 100, 30);

        Background.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\İmage\\Beyaz.jpg")); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 10, 340, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Veri_Ekleme veri_Ekleme=new Veri_Ekleme();
  ArrayList<String>Dizi=new ArrayList<>();
  Dizi.add(String.valueOf(Tc_jTextField.getText()));
   Dizi.add(String.valueOf(Yetkili_Kisi_jTextField.getText()));
    Dizi.add(String.valueOf(SabitTelefon_jTextField.getText()));
     Dizi.add(String.valueOf(CepTelefonu_jTextField.getText()));
      Dizi.add(String.valueOf(Adres_jTextPane1.getText()));
       Dizi.add(String.valueOf(Sirket_Ad_jTextField.getText()));
        Dizi.add(String.valueOf(EPosta_jTextField.getText()));
         Dizi.add(String.valueOf(VergiDairesi_jTextField.getText()));
          Dizi.add(String.valueOf(VergiNumarasi_jTextField.getText()));
           Dizi.add(String.valueOf(Iban_jTextField.getText()));
       
veri_Ekleme.kaydet(Dizi , "INSERT INTO musteri_listesi ( tc, Yetkili_Kisi, Aldigi_Urun_Miktari, Kazanc, Borcu, Sabit_Telefon, Cep_Telefon, Adres, Sirket_Ad,"
                  + " E_Posta, `Vergi Dairesi`, Vergi_No, Iban) VALUES ( ?, ?, 0, 0, 0, ?, ?, ?, ?, ?, ?, ?, ?)");
this.setVisible(false);
AnaSayfa_ sayfa_=new AnaSayfa_();
sayfa_.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtoncikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncikisActionPerformed
this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtoncikisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Musteri_EKle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Musteri_EKle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Musteri_EKle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Musteri_EKle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Musteri_EKle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane Adres_jTextPane1;
    private javax.swing.JLabel Background;
    private javax.swing.JTextField CepTelefonu_jTextField;
    private javax.swing.JTextField EPosta_jTextField;
    private javax.swing.JTextField Iban_jTextField;
    private javax.swing.JTextField SabitTelefon_jTextField;
    private javax.swing.JTextField Sirket_Ad_jTextField;
    private javax.swing.JTextField Tc_jTextField;
    private javax.swing.JTextField VergiDairesi_jTextField;
    private javax.swing.JTextField VergiNumarasi_jTextField;
    private javax.swing.JTextField Yetkili_Kisi_jTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtoncikis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
