/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veri_tabani_depo;

import java.beans.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author numan
 */
public class Popup_Table extends javax.swing.JFrame {
  Veri_Cekme cekme = new Veri_Cekme();
 Table_Veri table_Veri=new Table_Veri();
int asdsd=0;
String Gelecek_Veri1="";
String Gelecek_Veri2="";
int table1_Eklenen_Veri=0;
DefaultTableModel asd=new DefaultTableModel();
 String ads="";
      DefaultTableModel table_Urun_Secimi=new DefaultTableModel(){
      
        public boolean isCellEditable(int row, int col) {
                    return false;
                }
};

   DefaultTableModel table1=new DefaultTableModel(){

        public boolean isCellEditable(int row, int col) {
                    return false;
                }
};
   DefaultTableModel table2=new DefaultTableModel(){

        public boolean isCellEditable(int row, int col) {
                    return false;
                }
};
    public String getGelecek_Veri1() {
        return Gelecek_Veri1;
    }

    public void setGelecek_Veri1(String Gelecek_Veri1) {
        this.Gelecek_Veri1 = Gelecek_Veri1;
    }

    public String getGelecek_Veri2() {
        return Gelecek_Veri2;
    }

    public void setGelecek_Veri2(String Gelecek_Veri2) {
        this.Gelecek_Veri2 = Gelecek_Veri2;
    }
   Veri_Cekme cekme2=new Veri_Cekme();
    /**
     * Creates new form Popup_Table
     */
    public Popup_Table() {
        initComponents();
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nul1l", "nu2ll", "nu3ll", "nu4ll", "n5ull", "n6ull"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        

        
         table_Veri.Table_Veri("SELECT * FROM urunler1 u WHERE u.Kumas_cinsi='"+getGelecek_Veri2()+"' and u.Isim='"+getGelecek_Veri2()+"'",table1,table1_Eklenen_Veri);
            table1_Eklenen_Veri++;
         jTable1.setModel(table1);
         satisislemleri satisislemleri=new satisislemleri();
       
    }//GEN-LAST:event_jButton1ActionPerformed
public DefaultTableModel gonder(DefaultTableModel asd){
    
    
   return asd;
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
/* Table_Veri table_Veri=new Table_Veri();
 Satıs_Islemleri satıs_Islemleri=new Satıs_Islemleri();
 satıs_Islemleri.setGelecek_Sorgu(12123341);*/
  int table_Urun_Eklenen_Veri=0 ;
      
         Table_Veri table_Veri=new Table_Veri();
         table_Veri.Table_Veri("SELECT * FROM urunler1",table_Urun_Secimi,table_Urun_Eklenen_Veri);
    table_Urun_Eklenen_Veri++;
      
    table2=table_Urun_Secimi;
   gonder(table_Urun_Secimi);
      
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
try {
        ArrayList<String> numan = cekme.Veri_Cekme("SELECT * FROM urunler1 u WHERE u.Kumas_cinsi='"+getGelecek_Veri2()+"' and u.Isim='"+getGelecek_Veri2()+"'");
           JTable target = (JTable) evt.getSource();
            int row = target.getSelectedRow();
                        asdsd=Integer.valueOf(numan.get((row * 6) + 0));
            satisislemleri satisislemleri=new satisislemleri();
      //      satıs_Islemleri.metod(asdsd);
          ads=   satisislemleri.Sorgu;
      //      table.getDataVector().removeAllElements();
        //    table.setColumnCount(0);

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Stoklar.class.getName()).log(Level.SEVERE, null, ex);
        } 
   
    
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Popup_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Popup_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Popup_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Popup_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Popup_Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    // End of variables declaration//GEN-END:variables
}
