/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veri_tabani_depo;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author numan
 */
public class satisislemleri extends javax.swing.JFrame {
    java.util.ArrayList<String>bos  = new java.util.ArrayList<>();
private JLabel labelUsername = new JLabel("Enter username: ");
    private JLabel labelPassword = new JLabel("Enter password: ");
    private JTextField textUsername = new JTextField(20);
    private JPasswordField fieldPassword = new JPasswordField(20);
    private JButton buttonLogin = new JButton("Login");
  int[] selectedRows;
    int IsimSayac = 0;
    int TurSayac = 0;
    String Musteri_No;
    Table_Veri table_Veri=new Table_Veri();
      int table_Urun_Eklenen_Veri=0 ;
   int table_Musteri_Eklenen_Veri=0;
   int Mussteri_No;
      DefaultTableModel table_Urun_Secimi=new DefaultTableModel(){
      public boolean isCellEditable(int row, int col) {
                    return false;}};
   DefaultTableModel table_Musteri_Secimi=new DefaultTableModel(){
 public boolean isCellEditable(int row, int col) {
                    return false;}};
   java.util.ArrayList<String> dizi = new java.util.ArrayList<>();
   java.util.ArrayList<String> stringdizi,Taksit_Ekranina_GidenDizi = new java.util.ArrayList<>();
 
    Veri_Cekme cekme = new Veri_Cekme();
     DefaultTableModel table;
       Integer Gelecek_Sorgu;
      String Sorgu="";
    public Integer getGelecek_Sorgu() {
        return Gelecek_Sorgu;
    }

    public void setGelecek_Sorgu(Integer Gelecek_Sorgu) {
        this.Gelecek_Sorgu = Gelecek_Sorgu;
    }
   String ToplamFiyat;
     String ToplamKilo;
    String Silinecek_id;
    String Alinan_Urun;

    int ToplamKiloPara = 0;
    int ToplammFiyatt = 0;

    ArrayList<String> numan;

 
    Veri_Cekme cekme2 = new Veri_Cekme();
    public String GTable = "";

 
    /**
     * Creates new form SatÄ±s_Islemleri
     */
    public satisislemleri() {
  
        initComponents();
        this.setTitle("SatÄ±s Ä°slemler");
           this.setBounds(960, 100, 785, 520);
this.setResizable(false);
          setLocationRelativeTo(null);
    
        
        JcomboTur.setVisible(false);
        jComboBoxIsim.setVisible(false);
   Table_Veri table_Veri=new Table_Veri();
         table_Veri.Table_Veri("SELECT ml.musterino,ml.tc,ml.Aldigi_Urun_Miktari,ml.Kazanc,ml.Borcu,ml.Sirket_Ad  FROM musteri_listesi ml",table_Musteri_Secimi,table_Musteri_Eklenen_Veri);
      table_Musteri_Eklenen_Veri++;
  jTable1.setModel(table_Musteri_Secimi);
 
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelAd = new javax.swing.JLabel();
        jLabelBorc = new javax.swing.JLabel();
        jLabelTc = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jComboBoxIsim = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        JcomboTur = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        JLabelToplamFiyatYazi = new javax.swing.JLabel();
        jLabel1ToplamFiyat = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Musteri_Bilgisi_Label = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Toplam_Fiyat_jLabel = new javax.swing.JLabel();
        jLabelaldigiurunbilgisi = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabelUMusteriBilgisi_Yazi = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jButton1.setText("jButton1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel2.setLayout(null);

        jTable1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(153, 0, 0));
        jTable1.setOpaque(false);
        jTable1.setSelectionBackground(new java.awt.Color(153, 51, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 780, 160);

        jLabelAd.setBackground(new java.awt.Color(204, 204, 204));
        jLabelAd.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabelAd.setOpaque(true);
        jPanel2.add(jLabelAd);
        jLabelAd.setBounds(10, 240, 230, 40);

        jLabelBorc.setBackground(new java.awt.Color(204, 204, 204));
        jLabelBorc.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabelBorc.setOpaque(true);
        jPanel2.add(jLabelBorc);
        jLabelBorc.setBounds(510, 240, 230, 40);

        jLabelTc.setBackground(new java.awt.Color(204, 204, 204));
        jLabelTc.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabelTc.setOpaque(true);
        jPanel2.add(jLabelTc);
        jLabelTc.setBounds(260, 240, 230, 40);

        jLabel11.setBackground(new java.awt.Color(255, 51, 51));
        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 51, 0));
        jLabel11.setText("   << Adi Soyadi >>");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 200, 210, 30);

        jLabel12.setBackground(new java.awt.Color(153, 51, 0));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 51, 0));
        jLabel12.setText("<< TC&VergiNumarasi >>");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(260, 210, 230, 20);

        jLabel13.setBackground(new java.awt.Color(153, 51, 0));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 51, 0));
        jLabel13.setText("             << Borcu >>");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(510, 210, 230, 25);

        jLabel8.setBackground(new java.awt.Color(255, 51, 51));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 51, 0));
        jLabel8.setText("<<Secilen MÃ¼ÅŸteri Bilgisi>>");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 170, 330, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\Ä°mage\\Beyaz.jpg")); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(-20, -50, 800, 533);

        jTabbedPane1.addTab("MÃ¼steri", jPanel2);

        jPanel1.setLayout(null);

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(440, 40, 300, 31);

        jComboBoxIsim.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jComboBoxIsim.setPreferredSize(new java.awt.Dimension(101, 31));
        jComboBoxIsim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxIsimMouseClicked(evt);
            }
        });
        jPanel1.add(jComboBoxIsim);
        jComboBoxIsim.setBounds(10, 60, 310, 40);

        jLabel5.setBackground(new java.awt.Color(255, 51, 51));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText("<< Barkod Numarasi >>");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(470, 10, 240, 25);

        jTable3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable3.setDragEnabled(true);
        jTable3.setGridColor(new java.awt.Color(204, 204, 204));
        jTable3.setOpaque(false);
        jTable3.setSelectionBackground(new java.awt.Color(153, 51, 0));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable3);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(20, 140, 740, 180);

        JcomboTur.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        JcomboTur.setPreferredSize(new java.awt.Dimension(191, 31));
        JcomboTur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JcomboTurMouseClicked(evt);
            }
        });
        JcomboTur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboTurActionPerformed(evt);
            }
        });
        jPanel1.add(JcomboTur);
        JcomboTur.setBounds(10, 10, 310, 40);

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel15.setOpaque(true);
        jPanel1.add(jLabel15);
        jLabel15.setBounds(400, 390, 150, 40);

        JLabelToplamFiyatYazi.setBackground(new java.awt.Color(255, 51, 51));
        JLabelToplamFiyatYazi.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        JLabelToplamFiyatYazi.setForeground(new java.awt.Color(153, 51, 0));
        JLabelToplamFiyatYazi.setText("<< Toplam_Fiyat >>");
        jPanel1.add(JLabelToplamFiyatYazi);
        JLabelToplamFiyatYazi.setBounds(570, 330, 170, 40);

        jLabel1ToplamFiyat.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1ToplamFiyat.setOpaque(true);
        jPanel1.add(jLabel1ToplamFiyat);
        jLabel1ToplamFiyat.setBounds(580, 390, 150, 40);

        jButton4.setBackground(new java.awt.Color(153, 51, 0));
        jButton4.setText("Sil");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(340, 80, 80, 50);

        jLabel14.setBackground(new java.awt.Color(255, 51, 51));
        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 51, 0));
        jLabel14.setText("    << Toplam_Kilo >>");
        jLabel14.setFocusCycleRoot(true);
        jPanel1.add(jLabel14);
        jLabel14.setBounds(360, 330, 200, 40);

        jButton2.setBackground(new java.awt.Color(153, 51, 0));
        jButton2.setText("Ekle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(430, 80, 310, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\Ä°mage\\Beyaz.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-10, 10, 790, 440);

        jTabbedPane1.addTab("ÃœrÃ¼n Å�eÃ§imi", jPanel1);

        jPanel3.setLayout(null);

        jButton9.setBackground(new java.awt.Color(153, 51, 0));
        jButton9.setText("Nakit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9);
        jButton9.setBounds(440, 50, 280, 50);

        jButton7.setBackground(new java.awt.Color(153, 51, 0));
        jButton7.setText("Taksitli SatÄ±ÅŸ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(440, 120, 140, 50);

        Musteri_Bilgisi_Label.setBackground(new java.awt.Color(204, 204, 204));
        Musteri_Bilgisi_Label.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        Musteri_Bilgisi_Label.setOpaque(true);
        jPanel3.add(Musteri_Bilgisi_Label);
        Musteri_Bilgisi_Label.setBounds(230, 50, 180, 30);

        jButton11.setBackground(new java.awt.Color(153, 51, 0));
        jButton11.setText("Ä°skonto");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11);
        jButton11.setBounds(590, 190, 130, 50);

        jButton8.setBackground(new java.awt.Color(153, 51, 0));
        jButton8.setText("Cek");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(440, 190, 140, 50);

        Toplam_Fiyat_jLabel.setBackground(new java.awt.Color(204, 204, 204));
        Toplam_Fiyat_jLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Toplam_Fiyat_jLabel.setForeground(new java.awt.Color(153, 51, 0));
        Toplam_Fiyat_jLabel.setOpaque(true);
        jPanel3.add(Toplam_Fiyat_jLabel);
        Toplam_Fiyat_jLabel.setBounds(20, 150, 370, 160);

        jLabelaldigiurunbilgisi.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabelaldigiurunbilgisi.setForeground(new java.awt.Color(153, 51, 0));
        jLabelaldigiurunbilgisi.setText("               << AldÄ±ÄŸÄ± ÃœrÃ¼n Bilgisi >>");
        jPanel3.add(jLabelaldigiurunbilgisi);
        jLabelaldigiurunbilgisi.setBounds(20, 120, 370, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(45, 163, 240, 79);

        jButton13.setBackground(new java.awt.Color(153, 51, 0));
        jButton13.setText("CÄ±kÄ±ÅŸ");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13);
        jButton13.setBounds(440, 260, 280, 50);

        jLabelUMusteriBilgisi_Yazi.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabelUMusteriBilgisi_Yazi.setForeground(new java.awt.Color(153, 51, 0));
        jLabelUMusteriBilgisi_Yazi.setText("<< MÃ¼ÅŸteri Bilgisi >>");
        jPanel3.add(jLabelUMusteriBilgisi_Yazi);
        jLabelUMusteriBilgisi_Yazi.setBounds(10, 50, 210, 30);

        jButton10.setBackground(new java.awt.Color(153, 51, 0));
        jButton10.setText("SatÄ±s Bilgisi");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10);
        jButton10.setBounds(590, 120, 130, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\Ä°mage\\Beyaz.jpg")); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(0, -10, 820, 460);

        jTabbedPane1.addTab("SatÄ±s Onaylama", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        try {
            ArrayList<String> numan = cekme.Veri_Cekme("SELECT * FROM musteri_listesi ml");
            JTable target = (JTable) evt.getSource();
            int row = target.getSelectedRow();
  Musteri_Bilgisi_Label.setText("  " + numan.get((row * 14) + 2));
            jLabelBorc.setText("" + numan.get((row * 14) + 5));
            jLabelTc.setText("" + numan.get((row * 14) + 1));
            jLabelAd.setText("" + numan.get((row * 14) + 2));
           Mussteri_No=Integer.valueOf(numan.get((row * 14) + 0));  // veri1
          
         
   
            // TODO add your handling code here:
        } catch (SQLException ex) {
         
            Logger.getLogger(Stoklar.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked
 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
      table_Veri.Table_Veri("SELECT  *  FROM  urunler1 WHERE Barkod_No='" + jTextField1.getText() + "'",table_Urun_Secimi,table_Urun_Eklenen_Veri);
     table_Urun_Eklenen_Veri++;
 jTable3.setModel(table_Urun_Secimi);
        dizi.add((jTextField1.getText()));
        JTable target = new JTable();
        ToplamKilo = String.valueOf(table_Veri.cekme2.getRow().get( 3));
        ToplamFiyat = String.valueOf(table_Veri.cekme2.getRow().get( 5));
        Alinan_Urun=","+String.valueOf(table_Veri.cekme2.getRow().get(2));; 
        ToplamKiloPara = ToplamKiloPara + Integer.valueOf(ToplamKilo);
        ToplammFiyatt = ToplammFiyatt + Integer.valueOf(ToplamFiyat); 
        jLabel1ToplamFiyat.setText(String.valueOf(ToplamKiloPara));   
        jLabel15.setText(String.valueOf(ToplammFiyatt));
        double Kdvhesapla=(ToplammFiyatt/100)*8;
      //  Toplam_Fiyat_jLabel.setText(" <html>        " + "<br>Toplam Fiyat:"+jLabel15.getText()+" â‚º"+"");  
              Toplam_Fiyat_jLabel.setText("<html>ÃœrÃ¼n Fiyati :"+(ToplammFiyatt+Kdvhesapla)+"<br>Kdv Dahil Fiyat :"+Kdvhesapla+"</html>");
        ToplamKilo = "";
        ToplamFiyat="";
   


    }//GEN-LAST:event_jButton2ActionPerformed

    private void JcomboTurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboTurActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_JcomboTurActionPerformed

    private void JcomboTurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JcomboTurMouseClicked
        System.out.println("asd");
        TurSayac++;
        int a3 = jComboBoxIsim.getItemCount();
        if (TurSayac == 1 || a3 == 0) {
            Veri_Cekme cekme = new Veri_Cekme();
            try {
                ArrayList<String> JcomboBox = cekme.Veri_Cekme("SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE Table_Name='kumas_cinsleri'");
                for (int i = 0; i < JcomboBox.size(); i++) {
                    JcomboTur.addItem(JcomboBox.get(i));

                }

            } catch (SQLException ex) {
                Logger.getLogger(urungirisi.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jComboBoxIsim.removeAllItems();
            a3 = 0;
            TurSayac--;

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_JcomboTurMouseClicked

    private void jComboBoxIsimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxIsimMouseClicked

        IsimSayac++;
        if (IsimSayac == 1) {
            Veri_Cekme cekme = new Veri_Cekme();
            try {

                ArrayList<String> numan = cekme.Veri_Cekme("SELECT '" + (String) JcomboTur.getSelectedItem() + "' FROM  kumas_cinsleri");//hata var
                for (int i = 0; i < numan.size(); i++) {
                    jComboBoxIsim.addItem(numan.get(i));

                }

            } catch (SQLException ex) {
                Logger.getLogger(urungirisi.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            //doldur
        }
    
        Popup_Table pt = new Popup_Table();
        pt.setGelecek_Veri1("Suprem");
        pt.setGelecek_Veri2("Suprem");
        pt.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIsimMouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
selectedRows =jTable3.getSelectedRows();
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
   Veri_Ekleme veri_Ekleme = new Veri_Ekleme();
   Veri_Cekme cekme=new  Veri_Cekme();
   Veri_Silme vs = new Veri_Silme();
        try {
         
         String VeriTabaninaAciklama=String.valueOf(ToplamKiloPara)+"  Kilo   " +""+Alinan_Urun+"  AlÄ±nmÄ±ÅŸtÄ±r";
          // veri_Ekleme.kaydet(StringdÄ°ZÄ°, "INSERT INTO kasa (`Gelir-Giden`, AcÄ±klama, Toplam_Para, Kime_Kimden, Turu) VALUES (1, simdilik yok, '" + ToplammFiyatt + "','" + jLabelAd.getText() + "', Nakit);");
  //veri_Ekleme.kaydet(StringdÄ°ZÄ°, "INSERT INTO kasa (musterino,, AcÄ±klama, Toplam_Para, Turu) VALUES ('"+MÃ¼steri_No+"',1,'"+VeriTabanÄ±na_AcÄ±klama+"','"+ToplammFiyatt+"','"+jLabelAd.getText()+"', '0')");

      
  veri_Ekleme.kaydet(bos, "INSERT kasa ( `Gelir-Giden`, AcÄ±klama, Toplam_Para, musterino, Turu) VALUES ( 1, '"+VeriTabaninaAciklama+"',"+ToplammFiyatt+" ,"+Musteri_No+", '0')");
 cekme.Veri_Cekme("SELECT LAST_INSERT_ID(ml.Aldigi_Urun_Miktari) ss FROM musteri_listesi ml WHERE ml.musterino="+Musteri_No+"");
 int esv2=Integer.valueOf( cekme.getRow().get(cekme.getRow().size()-1));
  veri_Ekleme.kaydet(bos, "UPDATE musteri_listesi set Aldigi_Urun_Miktari = "+(ToplamKiloPara+esv2)+" WHERE musterino ="+Musteri_No+" ");

  vs.islemler("DELETE FROM urunler1 WHERE Barkod_No='"+jTextField1.getText()+"' ", bos);
  // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(satisislemleri.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton9ActionPerformed

   
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       Veri_Ekleme veri_Ekleme = new Veri_Ekleme();
        Veri_Silme vs = new Veri_Silme();
        try {
         
         String VeriTabaninaAciklama=String.valueOf(ToplamKiloPara)+"  Kilo   " +""+Alinan_Urun+"  AlÄ±nmÄ±ÅŸtÄ±r";
          // veri_Ekleme.kaydet(StringdÄ°ZÄ°, "INSERT INTO kasa (`Gelir-Giden`, AcÄ±klama, Toplam_Para, Kime_Kimden, Turu) VALUES (1, simdilik yok, '" + ToplammFiyatt + "','" + jLabelAd.getText() + "', Nakit);");
  //veri_Ekleme.kaydet(StringdÄ°ZÄ°, "INSERT INTO kasa (musterino,, AcÄ±klama, Toplam_Para, Turu) VALUES ('"+MÃ¼steri_No+"',1,'"+VeriTabanÄ±na_AcÄ±klama+"','"+ToplammFiyatt+"','"+jLabelAd.getText()+"', '0')");
  veri_Ekleme.kaydet(stringdizi, "INSERT kasa ( `Gelir-Giden`, AcÄ±klama, Toplam_Para, musterino, Turu) VALUES ( 1, '"+VeriTabaninaAciklama+"',"+ToplammFiyatt+" , "+Musteri_No+", '2')");

  vs.islemler("DELETE FROM urunler1 WHERE Barkod_No=?", dizi);
  // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(satisislemleri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
Taksit_Ekranina_GidenDizi.add(String.valueOf(ToplammFiyatt));
Taksit_Ekranina_GidenDizi.add(String.valueOf(ToplamKiloPara));
Taksit_Ekranina_GidenDizi.add(String.valueOf(Mussteri_No));
Taksit_Ekranina_GidenDizi.add(Alinan_Urun);
        Taksit_Ekrani taksit_Ekrani=new Taksit_Ekrani();
        taksit_Ekrani.Satis_Ekranindan_Gelen_Dizi(Taksit_Ekranina_GidenDizi,dizi);
        taksit_Ekrani.setVisible(true);
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

     
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if(table_Urun_Secimi.getRowCount()>0){
    if (selectedRows.length > 0) {
            for (int i = selectedRows.length - 1; i >= 0; i--) {
                table_Urun_Secimi.removeRow(selectedRows[i]);
            }
        } 
     /*  ToplamFiyat = String.valueOf(table_Veri.cekme2.getRow().get(selectedRows[0]));
ToplammFiyatt = ToplammFiyatt - Integer.valueOf(ToplamFiyat); 
  double Kdvhesapla=(ToplammFiyatt/100)*8;
          Toplam_Fiyat_jLabel.setText("<html>ÃœrÃ¼n Fiyati :"+(ToplammFiyatt+Kdvhesapla)+"<br>Kdv Dahil Fiyat :"+Kdvhesapla+"</html>");
 */   
}
       
 

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(satisislemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(satisislemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(satisislemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(satisislemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new satisislemleri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelToplamFiyatYazi;
    private javax.swing.JComboBox<String> JcomboTur;
    private javax.swing.JLabel Musteri_Bilgisi_Label;
    private javax.swing.JLabel Toplam_Fiyat_jLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBoxIsim;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel1ToplamFiyat;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAd;
    private javax.swing.JLabel jLabelBorc;
    private javax.swing.JLabel jLabelTc;
    private javax.swing.JLabel jLabelUMusteriBilgisi_Yazi;
    private javax.swing.JLabel jLabelaldigiurunbilgisi;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
