/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veri_tabani_depo;
import java.beans.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import  java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
 
import net.sourceforge.barbecue.BarcodeException;
import net.sourceforge.barbecue.output.OutputException;
import sun.awt.windows.WToolkit;
/**
 *
 * @author numan
 */
public class Stoklar extends javax.swing.JFrame {
int syc1=0,syc2=0;
int tablesayac=0;
String ColName;
String Text1;
 ResultSet       result;
  String SorguArama;
Veri_Cekme cekme=new Veri_Cekme();

String Silinecek_id;
   Veri_Cekme cekme2=new Veri_Cekme();
 Table_Veri table_Veri=new Table_Veri();
    /**
     * Creates new form Stoklar
     */
    public Stoklar() throws SQLException {
   
        initComponents();

   this.setBounds(960, 100, 820, 570);
this.setResizable(false);
          setLocationRelativeTo(null);
        this.setTitle("Stoklar");
       Urunler_jTable.setColumnSelectionAllowed(false);
 Urunler_jTable.setAutoCreateColumnsFromModel( true );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Arama_jTextField = new javax.swing.JTextField();
        Menu_jComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Urunler_jTable = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Barkod_No_jLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Urun_Grubu_jLabel = new javax.swing.JLabel();
        Urun_Adi_jLabel = new javax.swing.JLabel();
        satisfiyatijlabel = new javax.swing.JLabel();
        Toplam_Kilo_jLabel = new javax.swing.JLabel();
        Urun_Getir_jButton = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        cikis = new javax.swing.JButton();
        Background2 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        Arama_jTextField.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Arama_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arama_jTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(Arama_jTextField);
        Arama_jTextField.setBounds(330, 270, 213, 26);

        Menu_jComboBox.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Menu_jComboBox.setFocusCycleRoot(true);
        Menu_jComboBox.setFocusTraversalPolicyProvider(true);
        Menu_jComboBox.setInheritsPopupMenu(true);
        Menu_jComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_jComboBoxMouseClicked(evt);
            }
        });
        Menu_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_jComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(Menu_jComboBox);
        Menu_jComboBox.setBounds(60, 270, 200, 26);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("<<Arama Metni >>");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 240, 170, 20);

        jLabel2.setBackground(new java.awt.Color(153, 51, 0));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("<< Herhangi Bir Sütün ile Arama >>");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 230, 330, 30);

        Urunler_jTable.setBackground(new java.awt.Color(204, 204, 204));
        Urunler_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Urunler_jTable.setCellSelectionEnabled(true);
        Urunler_jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Urunler_jTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Urunler_jTable);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 300, 800, 210);

        jButton11.setBackground(new java.awt.Color(153, 51, 0));
        jButton11.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Ara");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(560, 250, 127, 30);

        jButton1.setBackground(new java.awt.Color(153, 51, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ürün Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(530, 0, 110, 53);

        jButton2.setBackground(new java.awt.Color(153, 51, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ürün Gruplari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(530, 120, 110, 53);

        jButton4.setBackground(new java.awt.Color(153, 51, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Toplu Ürün Sil");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(660, 0, 130, 53);

        jButton3.setBackground(new java.awt.Color(153, 51, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Barkod Yazdır");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(530, 60, 260, 53);

        jButton6.setBackground(new java.awt.Color(153, 51, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Asgari Stok Altındaki Ürünler");
        jButton6.setToolTipText("");
        getContentPane().add(jButton6);
        jButton6.setBounds(650, 120, 140, 52);

        jButton7.setBackground(new java.awt.Color(153, 51, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Sayım");
        getContentPane().add(jButton7);
        jButton7.setBounds(410, 180, 380, 40);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText("Barkod No:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 10, 80, 22);

        Barkod_No_jLabel.setForeground(new java.awt.Color(153, 51, 0));
        Barkod_No_jLabel.setOpaque(true);
        getContentPane().add(Barkod_No_jLabel);
        Barkod_No_jLabel.setBounds(130, 10, 200, 22);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setText("Ürün Grubu:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 50, 80, 20);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 0));
        jLabel6.setText("Ürünün Adi:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 90, 80, 22);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 51, 0));
        jLabel8.setText("Satış Fiyati:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 130, 90, 22);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 51, 0));
        jLabel9.setText("Toplam:Kilo");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 180, 90, 21);

        Urun_Grubu_jLabel.setForeground(new java.awt.Color(153, 51, 0));
        Urun_Grubu_jLabel.setOpaque(true);
        getContentPane().add(Urun_Grubu_jLabel);
        Urun_Grubu_jLabel.setBounds(130, 49, 200, 20);

        Urun_Adi_jLabel.setForeground(new java.awt.Color(153, 51, 0));
        Urun_Adi_jLabel.setOpaque(true);
        getContentPane().add(Urun_Adi_jLabel);
        Urun_Adi_jLabel.setBounds(130, 90, 200, 20);

        satisfiyatijlabel.setForeground(new java.awt.Color(153, 51, 0));
        satisfiyatijlabel.setOpaque(true);
        getContentPane().add(satisfiyatijlabel);
        satisfiyatijlabel.setBounds(130, 130, 200, 22);

        Toplam_Kilo_jLabel.setForeground(new java.awt.Color(153, 51, 0));
        Toplam_Kilo_jLabel.setOpaque(true);
        getContentPane().add(Toplam_Kilo_jLabel);
        Toplam_Kilo_jLabel.setBounds(130, 180, 200, 21);

        Urun_Getir_jButton.setBackground(new java.awt.Color(153, 51, 0));
        Urun_Getir_jButton.setForeground(new java.awt.Color(255, 255, 255));
        Urun_Getir_jButton.setText("Ürünleri Getir");
        Urun_Getir_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Urun_Getir_jButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Urun_Getir_jButton);
        Urun_Getir_jButton.setBounds(410, 0, 111, 48);

        jButton9.setBackground(new java.awt.Color(153, 51, 0));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Ürün Sil");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(410, 58, 110, 50);

        jButton10.setBackground(new java.awt.Color(153, 51, 0));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Yenile");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(410, 120, 110, 50);

        cikis.setBackground(new java.awt.Color(153, 51, 0));
        cikis.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        cikis.setForeground(new java.awt.Color(255, 255, 255));
        cikis.setText("Cıkıs");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });
        getContentPane().add(cikis);
        cikis.setBounds(700, 250, 80, 30);

        Background2.setBackground(new java.awt.Color(204, 204, 204));
        Background2.setOpaque(true);
        getContentPane().add(Background2);
        Background2.setBounds(0, 0, 400, 220);

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\İmage\\Beyaz.jpg")); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, -20, 880, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Urun_Getir_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Urun_Getir_jButtonActionPerformed
DefaultTableModel table=new DefaultTableModel(){

        public boolean isCellEditable(int row, int col) {
                    return false;
                }
};
 table_Veri.Table_Veri("SELECT * FROM urunler1", table, tablesayac);
    
    Urunler_jTable.setModel(table);
    
         
        // TODO add your handling code here:
    }//GEN-LAST:event_Urun_Getir_jButtonActionPerformed

    private void Urunler_jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Urunler_jTableMouseClicked
    try {
        ArrayList<String>numan=cekme.Veri_Cekme("select * FROM  urunler1" );
        JTable target = (JTable)evt.getSource();
        int row = target.getSelectedRow();
        int column = target.getSelectedColumn();
        Barkod_No_jLabel.setText(numan.get((row*6)));
        Urun_Grubu_jLabel.setText(numan.get((row*6)+2));
        Urun_Adi_jLabel.setText(numan.get((row*6)+1));
        satisfiyatijlabel.setText(numan.get((row*6)+5));
        Toplam_Kilo_jLabel.setText(numan.get((row*6)+3));
        Silinecek_id=String.valueOf(numan.get((row*6)+0));
        //  System.out.println(numan.subList(row-1,0));
        System.out.println("<<<<"+numan.get(row*6));
        System.out.println(numan.get(5));
        System.out.println(numan.get(10));
        
        
        // TODO add your handling code here:
    } catch (SQLException ex) {
        Logger.getLogger(Stoklar.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_Urunler_jTableMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
   
  Veri_Silme silme=new Veri_Silme();
    try {
        silme.islemler("DELETE FROM urunler1 WHERE Id='"+Integer.valueOf(Silinecek_id)+"'",null);
        // TODO add your handling code here:
    } catch (Exception ex) {
        Logger.getLogger(Stoklar.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
    try { 
    
   
        ArrayList<String>numan=cekme2.Veri_Cekme("select * FROM  urunler1" );
    } catch (SQLException ex) {
        Logger.getLogger(Stoklar.class.getName()).log(Level.SEVERE, null, ex);
    }
DefaultTableModel table=new DefaultTableModel(){

        public boolean isCellEditable(int row, int col) {
                    return false;
                }
};
int a=cekme2.getColumnCount(); 
Object[] aa=new Object[a];
      int j=1;    
try {
               for (int i = 1; i <= a; i++) {
                    table.addColumn(cekme2.dizi[i-1]);
                    Menu_jComboBox.addItem(cekme2.dizi[i-1]);
               }
               int asd=cekme2.getRow().size();
               for (int i = 1; i <= cekme2.getRow().size(); i++) {
              if (i%a==0) { 
                  table.addRow(aa); 
                         aa[j-1]=cekme2.row.get(i-1);
                j=1;   }
                   else{
                  aa[j-1]=cekme2.row.get(i-1);
                             j++; 
                   }
              
               } Urunler_jTable.setModel(table);
           }
    catch (Exception ex) {
      
    }  
 
      
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   urungirisi urungirisi=new urungirisi();
   urungirisi.setVisible(true);
   return ;

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Urun_Gruplari gruplari=new Urun_Gruplari();
gruplari.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Arama_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arama_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Arama_jTextFieldActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
 DefaultTableModel table=new DefaultTableModel(){

        public boolean isCellEditable(int row, int col) {
                    return false;
                }
};
        ColName=String.valueOf(Menu_jComboBox.getSelectedItem());
 Text1=Arama_jTextField.getText();
SorguArama="SELECT * FROM urunler1 u WHERE "+ColName+" LIKE '"+Text1+"%'";
table_Veri.Table_Veri(SorguArama, table, syc2);

Urunler_jTable.setModel(table);


    }//GEN-LAST:event_jButton11ActionPerformed

    private void Menu_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_jComboBoxActionPerformed
      
         // TODO add your handling code here:
    }//GEN-LAST:event_Menu_jComboBoxActionPerformed

    private void Menu_jComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_jComboBoxMouseClicked
        syc1++;
     if (syc1==1) {
              Veri_Cekme cekme=new Veri_Cekme();
        try {
                ArrayList<String>numan=cekme.Veri_Cekme("SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE Table_Name='urunler1'");
        for (int i = 0; i < numan.size(); i++) {
           Menu_jComboBox.addItem(numan.get(i));
           
           }
     
        
        } catch (SQLException ex) {
            Logger.getLogger(urungirisi.class.getName()).log(Level.SEVERE, null, ex);
        }}  // TODO add your handling code here:
    }//GEN-LAST:event_Menu_jComboBoxMouseClicked

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_cikisActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Toplu_Urun_Sil sil=new Toplu_Urun_Sil();
sil.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String Barkod=Barkod_No_jLabel.getText();
        Olusturma olusturma=new Olusturma();
    try {
        olusturma.asd(Barkod);
        
        
        
        // TODO add your handling code here:
    } catch (BarcodeException ex) {
        Logger.getLogger(Stoklar.class.getName()).log(Level.SEVERE, null, ex);
    } catch (OutputException ex) {
        Logger.getLogger(Stoklar.class.getName()).log(Level.SEVERE, null, ex);
    }
    ciktialim cikti=new ciktialim();
  

         cikti.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stoklar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stoklar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stoklar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stoklar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Stoklar().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Stoklar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Arama_jTextField;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Background2;
    private javax.swing.JLabel Barkod_No_jLabel;
    private javax.swing.JComboBox<String> Menu_jComboBox;
    private javax.swing.JLabel Toplam_Kilo_jLabel;
    private javax.swing.JLabel Urun_Adi_jLabel;
    private javax.swing.JButton Urun_Getir_jButton;
    private javax.swing.JLabel Urun_Grubu_jLabel;
    private javax.swing.JTable Urunler_jTable;
    private javax.swing.JButton cikis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel satisfiyatijlabel;
    // End of variables declaration//GEN-END:variables
}
