/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veri_tabani_depo;

import java.awt.List;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author numan
 */
public class Toplu_Urun_Sil extends javax.swing.JFrame {
Veri_Cekme cekme=new Veri_Cekme();
 DefaultTableModel table;
 int sayac=0,sayac1=0,syc2=0,SayacList=0;
 String combo1,combo2;
 String SorguArama;
 int[] selectedRows;
 String aasd;
 java.util.ArrayList<String>bos  = new java.util.ArrayList<>();

  DefaultTableModel table2=new DefaultTableModel();
  Table_Veri table_Veri=new Table_Veri();
  /**
     * Creates new form Toplu_Urun_Sil
     */
    public Toplu_Urun_Sil() {
        initComponents();

          this.setBounds(960, 100, 590, 375);
this.setResizable(false);
          setLocationRelativeTo(null);
        this.setTitle("Toplu Urun Sil ");
    }
 public void ru(){
              try { 
    
   
        java.util.ArrayList<String>numan=cekme.Veri_Cekme("select * FROM  urunler1" );
    } catch (SQLException ex) {
        Logger.getLogger(Stoklar.class.getName()).log(Level.SEVERE, null, ex);
    }
table=new DefaultTableModel(){

        public boolean isCellEditable(int row, int col) {
                    return false;
                }
}; 
int a=cekme.getColumnCount(); 
Object[] aa=new Object[a];
      int j=1;    
try {
               for (int i = 1; i <= a-4; i++) {
                    table.addColumn(cekme.dizi[i-1]);
                 table2.addColumn(cekme.dizi[i-1]);
               }
               table.addColumn(cekme.dizi[4]);
               
               int asd=cekme.getRow().size();
               for (int i = 1; i <= cekme.getRow().size(); i++) {
              if (i%a==0) { 
                  table.addRow(aa); 
                         aa[j-1]=cekme.row.get(i-1);
                j=1;   }
                   else{
                  aa[j-1]=cekme.row.get(i-1);
                             j++; 
                   }
              
               } jTable2.setModel(table);
              
           }
    catch (Exception ex) {
      
    }  
 
        
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        list1 = new java.awt.List();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("Barkod No");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 120, 26);

        jTextField1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 51, 0));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(100, 10, 190, 26);

        jLabel2.setBackground(new java.awt.Color(153, 51, 0));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("Ürün Grubu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 40, 130, 25);

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(100, 50, 190, 22);

        jTable2.setBackground(new java.awt.Color(204, 204, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable2.setGridColor(new java.awt.Color(204, 204, 255));
        jTable2.setInheritsPopupMenu(true);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(1, 137, 290, 200);

        jButton2.setBackground(new java.awt.Color(153, 51, 0));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(490, 280, 90, 50);

        jLabel3.setBackground(new java.awt.Color(153, 51, 0));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText(" Silinecek Ürün Listesi");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 10, 190, 16);

        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(100, 80, 190, 22);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("Ürün Adi");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 80, 80, 20);

        jButton3.setBackground(new java.awt.Color(153, 51, 0));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Getir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(0, 110, 290, 29);

        list1.setBackground(new java.awt.Color(204, 204, 255));
        list1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        list1.setForeground(new java.awt.Color(153, 51, 0));
        jPanel1.add(list1);
        list1.setBounds(300, 40, 177, 238);

        jButton1.setBackground(new java.awt.Color(153, 51, 0));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tabloyu Temizle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 280, 180, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\İmage\\Beyaz.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(-9, 6, 610, 340);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 341);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
 
       
        aasd=String.valueOf(jTable2.getModel().getValueAt(SayacList, 0));
 list1.add(aasd);
        SayacList++;
    }//GEN-LAST:event_jTable2MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed




        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
      sayac++;
        if (sayac==1) {
              Veri_Cekme cekme=new Veri_Cekme();
        try {
                ArrayList<String>numan=cekme.Veri_Cekme("SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE Table_Name='kumas_cinsleri'");
        for (int i = 0; i < numan.size(); i++) {
           jComboBox1.addItem(numan.get(i));
           
           }
     
        
        } catch (SQLException ex) {
            Logger.getLogger(urungirisi.class.getName()).log(Level.SEVERE, null, ex);
        }     
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
   sayac1++;
        if (sayac1==1) {
           Veri_Cekme cekme=new Veri_Cekme();
        try {
            String a=(String) jComboBox1.getSelectedItem();
            ArrayList<String>numan=cekme.Veri_Cekme("SELECT "+a+" FROM  kumas_cinsleri" );//hata var
        for (int i = 0; i < numan.size(); i++) {
           jComboBox2.addItem(numan.get(i));
           
           }
   
        } catch (SQLException ex) {
            Logger.getLogger(urungirisi.class.getName()).log(Level.SEVERE, null, ex);
        }      
        }
        else sayac=0;
             // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 DefaultTableModel table=new DefaultTableModel(){

        public boolean isCellEditable(int row, int col) {
                    return false;
                }
};
        combo1=String.valueOf(jComboBox1.getSelectedItem());
  combo2=String.valueOf(jComboBox2.getSelectedItem());
SorguArama="SELECT * FROM urunler1 WHERE  Kumas_cinsi='"+combo1+"' and  Isim='"+combo2+"' OR Barkod_No='"+jTextField1.getText()+"'  ";
table_Veri.Table_Veri(SorguArama, table, syc2);

jTable2.setModel(table);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Veri_Silme veri_Silme=new Veri_Silme();
int a=list1.getItemCount();
        for (int i = 0; i < a; i++) {
    try {
        veri_Silme.islemler("DELETE FROM urunler1 WHERE Barkod_No='"+list1.getItem(i)+"'", bos);
    } catch (Exception ex) {
        Logger.getLogger(Toplu_Urun_Sil.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        }
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

list1.removeAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Toplu_Urun_Sil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Toplu_Urun_Sil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Toplu_Urun_Sil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Toplu_Urun_Sil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Toplu_Urun_Sil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private java.awt.List list1;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
