/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veri_tabani_depo;

import java.awt.event.KeyEvent;

/**
 *
 * @author numan
 */
public class Urun_Gruplari_Ekleme extends javax.swing.JFrame {

    /**
     * Creates new form Urun_Gruplari_Ekleme
     */
    public Urun_Gruplari_Ekleme() {
    
        initComponents();
        this.setBounds(575, 250, 417, 320);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        uyari = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(153, 51, 0));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\Delete.png")); // NOI18N
        jButton1.setText("Vazgeç");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(202, 147, 198, 54);

        jTextField1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 51, 0));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(0, 86, 400, 54);

        jButton2.setBackground(new java.awt.Color(153, 51, 0));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\save.png")); // NOI18N
        jButton2.setText("Ekle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 147, 195, 54);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("Yeni Ürün Grubunun Adi");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 40, 400, 39);

        uyari.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        uyari.setForeground(new java.awt.Color(153, 51, 0));
        uyari.setText(".");
        jPanel1.add(uyari);
        uyari.setBounds(40, 10, 260, 30);

        BackGround.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\İmage\\Beyaz.jpg")); // NOI18N
        BackGround.setText("jLabel3");
        jPanel1.add(BackGround);
        BackGround.setBounds(-9, -4, 410, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   java.util.ArrayList<String>dizi=new  java.util.ArrayList<>();
        Veri_Ekleme  veri_Ekleme=new Veri_Ekleme();
     
   
        veri_Ekleme.kaydet(dizi, "ALTER TABLE  kumas_cinsleri ADD "+jTextField1.getText()+" varchar(123)");
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
     String value = jTextField1.getText();
    int l = value.length();
     if (l==11) {
            jTextField1.setEnabled(false);
        }
  
    if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9'  || evt.getKeyChar()=='.' || evt.getKeyChar()==KeyEvent.VK_DELETE || evt.getKeyChar()==KeyEvent.VK_BACK_SPACE ) {
    
  jTextField1.setEditable(false);
        uyari.setText("* Lütfen (A-Z) Değerlerini Giriniz");
    } else {
          jTextField1.setEditable(true);
        uyari.setText("");
        }  

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Urun_Gruplari_Ekleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Urun_Gruplari_Ekleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Urun_Gruplari_Ekleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Urun_Gruplari_Ekleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Urun_Gruplari_Ekleme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel uyari;
    // End of variables declaration//GEN-END:variables
}
