/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veri_tabani_depo;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;

/**
 *
 * @author numan
 */
public class urungirisi extends javax.swing.JFrame {
int sayac=0;
int sayac1=0;
String Urun_id_Bulma;
    JOptionPane jOptionPane=new JOptionPane();
    ciktialim ciktialim=new ciktialim();
    /**
     * Creates new form Urun_Gırısı
     */
    public urungirisi() {
        initComponents();
    
           this.setBounds(960, 100, 440, 340);

          setLocationRelativeTo(null);
                this.setResizable(false);



setTitle("Urun girisi"); 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        TurCombo = new javax.swing.JComboBox<>();
        isimcombo = new javax.swing.JComboBox<>();
        TextKilo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Bacground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel6.setBackground(new java.awt.Color(153, 51, 0));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 0));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 0, 230, 30);

        TurCombo.setBackground(new java.awt.Color(216, 221, 208));
        TurCombo.setFocusCycleRoot(true);
        TurCombo.setMinimumSize(new java.awt.Dimension(111, 122));
        TurCombo.setPreferredSize(new java.awt.Dimension(91, 212));
        TurCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TurComboMouseClicked(evt);
            }
        });
        TurCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TurComboActionPerformed(evt);
            }
        });
        getContentPane().add(TurCombo);
        TurCombo.setBounds(210, 40, 210, 40);

        isimcombo.setBackground(new java.awt.Color(216, 221, 208));
        isimcombo.setMinimumSize(new java.awt.Dimension(90, 22));
        isimcombo.setPreferredSize(new java.awt.Dimension(90, 22));
        isimcombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isimcomboMouseClicked(evt);
            }
        });
        isimcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isimcomboActionPerformed(evt);
            }
        });
        getContentPane().add(isimcombo);
        isimcombo.setBounds(210, 90, 210, 40);

        TextKilo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextKiloMouseClicked(evt);
            }
        });
        TextKilo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextKiloKeyPressed(evt);
            }
        });
        getContentPane().add(TextKilo);
        TextKilo.setBounds(210, 150, 210, 30);

        jLabel3.setBackground(new java.awt.Color(216, 221, 208));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("İsim");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 90, 170, 38);

        jLabel2.setBackground(new java.awt.Color(216, 221, 208));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Tür");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 40, 170, 34);

        jLabel4.setBackground(new java.awt.Color(216, 221, 208));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Kilo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 170, 30);

        jButton2.setBackground(new java.awt.Color(153, 51, 0));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\Delete.png")); // NOI18N
        jButton2.setMnemonic(Bacground.getDebugGraphicsOptions());
        jButton2.setText("Temizle");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 220, 200, 61);

        jButton1.setBackground(new java.awt.Color(153, 51, 0));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\save.png")); // NOI18N
        jButton1.setText("Kaydet");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(226, 220, 190, 61);

        jButton3.setBackground(new java.awt.Color(153, 51, 0));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\exit.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(310, 0, 110, 41);

        Bacground.setIcon(new javax.swing.ImageIcon("C:\\Users\\numan.DESKTOP-BO05F21\\Documents\\NetBeansProjects\\Veri_Tabani_Depo\\İmage\\Beyaz.jpg")); // NOI18N
        getContentPane().add(Bacground);
        Bacground.setBounds(0, -10, 440, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyyMMdd");
LocalDate localDate = LocalDate.now();
String Date=dtf.format(localDate);

        String Barkod;
   String Id_No="";
    Urun_id_Bulma=String.valueOf(TurCombo.getSelectedIndex())+""+String.valueOf(isimcombo.getSelectedIndex());
    Barkod=(Urun_id_Bulma)+""+TextKilo.getText()+""+Date;
   
    
    ArrayList<String>ButtonDizi=new ArrayList<>();
       ButtonDizi.add(String.valueOf(Barkod));
      ButtonDizi.add(String.valueOf(Urun_id_Bulma));
     ButtonDizi.add((String)TurCombo.getSelectedItem());
    ButtonDizi.add(TextKilo.getText());
    ButtonDizi.add((String)isimcombo.getSelectedItem());
 
            try {
            if (TurCombo.getSelectedIndex()+1>0|| isimcombo.getSelectedIndex()+1>0  || TextKilo.getText().length()>0 ) {
                
                Veri_Ekleme ekleme=new Veri_Ekleme();
   ekleme.kaydet(ButtonDizi,"INSERT urunler1 (Barkod_No,Urun_Id, Kumas_cinsi, Kilo, Isim, Birim_Fiyati) VALUES (?, ?,?, ?, ?, '123')" );

   this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);                  
 
  this.invalidate();
this.validate();
this.repaint();
Olusturma olusturma=new Olusturma();
olusturma.asd(Barkod);
ciktialim.setVisible(true);
  JOptionPane.showMessageDialog(null, "Ürün Basarıyla Kaydedildi...");  
            }
            else{
                         
 
                   JOptionPane.showMessageDialog(null, "Lütfen Tekrar Deneyiniz");
       
            }
  
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Sistemde Sıkıntı var Lütfen Biraz Sonra Tekrar Deneyiniz");
  
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TurComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TurComboActionPerformed

  
    }//GEN-LAST:event_TurComboActionPerformed

    private void isimcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isimcomboActionPerformed
  

        
        
    }//GEN-LAST:event_isimcomboActionPerformed

    private void TurComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TurComboMouseClicked
       sayac++;
        if (sayac==1) {
              Veri_Cekme cekme=new Veri_Cekme();
        try {
                ArrayList<String>numan=cekme.Veri_Cekme("SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE Table_Name='kumas_cinsleri'");
        for (int i = 0; i < numan.size(); i++) {
           TurCombo.addItem(numan.get(i));
           
           }
     
        
        } catch (SQLException ex) {
            //Logger.getLogger(urungirisi.class.getName()).log(Level.SEVERE, null, ex);
        }     
        }
    
             
           // TODO add your handling code here:
    }//GEN-LAST:event_TurComboMouseClicked

    private void isimcomboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isimcomboMouseClicked
       sayac1++;
        if (sayac1==1) {
           Veri_Cekme cekme=new Veri_Cekme();
        try {
            String a=(String) TurCombo.getSelectedItem();
            ArrayList<String>numan=cekme.Veri_Cekme("SELECT "+a+" FROM  kumas_cinsleri" );//hata var
        for (int i = 0; i < numan.size(); i++) {
           isimcombo.addItem(numan.get(i));
           
           }
   
        } catch (SQLException ex) {
            Logger.getLogger(urungirisi.class.getName()).log(Level.SEVERE, null, ex);
        }      
        }
        else sayac=0;
     
                    // TODO add your handling code here:
    }//GEN-LAST:event_isimcomboMouseClicked

    private void TextKiloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextKiloKeyPressed
      
        
 
    if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9'  || evt.getKeyChar()=='.' || evt.getKeyChar()==KeyEvent.VK_DELETE || evt.getKeyChar()==KeyEvent.VK_BACK_SPACE ) {
        TextKilo.setEditable(true);
        jLabel6.setText("");
    } else {
        TextKilo.setEditable(false);
        jLabel6.setText("* Lütfen (0-9) Değerlerini Giriniz");
        }  
        // TextKilo.setText(TextKilo.getText().substring(0,10));
  // TODO add your handling code here:
    }//GEN-LAST:event_TextKiloKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
TurCombo.removeAllItems();
isimcombo.removeAllItems();
isimcombo.removeAll();
TextKilo.setText("");
  TextKilo.setEnabled(true);

            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
//AnaSayfa_ anaSayfa_=new AnaSayfa_();
//anaSayfa_.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_OPENED));
this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TextKiloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextKiloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TextKiloMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(urungirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(urungirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(urungirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(urungirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new urungirisi().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bacground;
    private javax.swing.JTextField TextKilo;
    private javax.swing.JComboBox<String> TurCombo;
    private javax.swing.JComboBox<String> isimcombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
